version: '3.8'

services:
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        env_file:
            - .env
        command: npm run start:prod
        ports:
            - 5000:5000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:

            - /usr/src/app/node_modules
        restart: unless-stopped
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        env_file:
            - .env.development
        command: npm run start:debug-watch
        ports:
            - 8000:8000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
networks:
    nesjs-network: